md "Todos os clubes"
cd "Todos os clubes"
md "Serie A"
md "Serie B"
cd "Serie A"
md "Atletico MG"
md "Palmeiras"
md "Fortaleza"
md "Bragantino"
md "Flamengo"
md "Athletico PR"
md "Atletico GO"
md "Ceara"
md "Internacional"
md "Santos"
md "Corinthians"
md "Juventude"
md "Bahia"
md "Sao Paulo"
md "Fluminense"
md "Cuiaba"
md "Sport"
md "America MG"
md "Gremio"
md "Chapecoense"

cd ..
cd "Serie B"
md "Coritiba" "Goias" "Avai" "CRB" "Sampaio Correa" "Guarani" "Nautico" "Botafogo" "Operario PR" "CSA" "Vasco" "Remo" "Brusque" "Cruzeiro" "Vila Nova" "Ponte Preta" "Londrina" "Vitoria" "Confianca" "Brasil de Pelotas"


